apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8-e209"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8-e209"
  template:
    metadata:
      labels:
        app: "k8-e209"
    spec:
      containers:
        - name: "k8-e209"
          image: "expressstest.azurecr.io/k8"
          ports:
          - containerPort: 3000